name: Prep - Release - Publish

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  prep:
    runs-on: ubuntu-latest

    steps:
    - name: Upload dist folder
      uses: actions/upload-artifact@v3.1.3
      with:
        name: distArtifact
        path: dist

  release:
    needs: prep
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dist folder
        uses: actions/download-artifact@2.1.1
        with:
          name: distArtifact
          path: dist

      - name: Show dist directory contents
        run: |
          cd dist
          ls

      - name: Create tarball
        run: tar -zcvf dist.tar.gz dist

      - name: Delete previous latest
        env:
          GH_TOKEN: ${{github.token}}
        run: gh release delete latest --yes

      - name: Make a new release with tarball
        env:
          GH_TOKEN: ${{github.token}}
        run: gh release create latest dist.tar.gz --notes-file changelog.md --latest

  publish:
    needs: [prep, release]
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dist folder
        uses: actions/download-artifact@v2.1.1
        with:
          name: distArtifact
          path: dist

      - name: Pack for NPM
        run: npm pack

      - name: Release to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMAUTHTOKENFORGITHUBONTARIOLRC}}
        run: npm publish --tag latest --access public
